sudo: false
language: python
install: pip install tox
script: tox
matrix:
  include:
    - python: 3.7
      env: TOXENV=lint
    - python: 3.7
      env: TOXENV=pep8
  # - python: 3.7
  #  env: TOXENV=py37
