# Pod structure, currently only controller and compute types are allowed.
pod:
  controller:
    - control:
        host_ip: 192.168.56.4
  compute:
    - compute-1:
        host_ip: 192.168.56.3
    # - compute-2:
    #    host_ip: 192.168.56.5

# SSH private key for connecting to the pod
ansible_ssh_private_key_file: ~/.ssh/id_rsa

# For now, it supports only one controller. This IP used by compute nodes.
controller_ip: 192.168.56.4

# Devstack repository and the version
devstack_repo: https://github.com/openstack-dev/devstack.git
devstack_version: c7114582c0b88f379cae795c8bc88bf840d0965a # e46f22db7fcb6e9aae5922d650eda14a15231fb8

# If network_configure is false, interfaces file will not be modified.
network_configure: true
interface_dhcp: True
interface_name: enp0s8
interface_netmask: 255.255.255.128 # if interface_dhcp = False
interface_gateway: 79.123.177.1 # if interface_dhcp = False
interface_dns_nameservers: 79.123.177.5 # if interface_dhcp = False
interface_dns_search: cmpe.boun.edu.tr # if interface_dhcp = False

# Openstack configurations
openstack_admin_password: cloudran
openstack_fixed_ip_range: 10.1.0.0/20
openstack_floating_ip_range: 172.24.5.0/24
openstack_openrc_path: /opt/stack/devstack/openrc
openstack_public_network_gateway: 172.24.5.1
openstack_service_token: supersecrettoken

# Host username
username: cloudran

# Check if it is a virtualbox based pod, it will affect the interface configuration.
virtualbox_pod: true


