- name: Copy local.conf file
  template:
    src: local.conf.j2
    dest: ~/devstack/local.conf
  when: install is defined and install

- name: Install devstack
  command: ~/devstack/stack.sh
  register: devstack
  when: install is defined and install

- name: test
  debug:
    msg: " {{ item.key }}"
  with_dict: "{{ pod.compute }}"

- name: Copy ceph configurations to compute nodes
  synchronize:
    src: /etc/ceph/*
    dest: /etc/ceph/
    mode: pull
  delegate_to: "{{ item.key }}"
  with_dict: "{{ pod.compute }}"

- include_tasks: post_install.yaml
  when: post_install is defined and post_install


